package co.com.amdocs.vo;

public class usingSimcard {
private String USINGSIMCARDPREPAG;
private String USINGSIMCARDPREPAG1;
public String getUSINGSIMCARDPREPAG() {
	return USINGSIMCARDPREPAG;
}
public void setUSINGSIMCARDPREPAG(String uSINGSIMCARDPREPAG) {
	USINGSIMCARDPREPAG = uSINGSIMCARDPREPAG;
}
public String getUSINGSIMCARDPREPAG1() {
	return USINGSIMCARDPREPAG1;
}
public void setUSINGSIMCARDPREPAG1(String uSINGSIMCARDPREPAG1) {
	USINGSIMCARDPREPAG1 = uSINGSIMCARDPREPAG1;
}
}
